version: "3"
services:
  app:
    build:
      context: .  # path to application's Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://rails_user_management:postgres@db:5432/rails_user_management_development
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: rails_user_management
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rails_user_management_development

