default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_user_management_development
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: rails_user_management_production
  url: <%= ENV['DATABASE_URL'] %>
  username: rails_user_management
  password: <%= ENV["RAILS_USER_MANAGEMENT_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: rails_user_management_test
  url: <%= ENV['DATABASE_URL'] %>
